[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
    "-C", "link-arg=--target=x86_64-linux-musl",
    "-C", "link-self-contained=yes",
]

[build]
rustc-wrapper = "sccache"
